/*
 * Copyright (c) 2022. PortSwigger Ltd. All rights reserved.
 *
 * This code may be used to extend the functionality of Burp Suite Community Edition
 * and Burp Suite Professional, provided that this usage does not violate the
 * license terms for those products.
 */

package burp.api.montoya.scanner.audit.issues;

/**
 * This interface is used to retrieve background information about audit
 * issues. Note that text generated by extensions is subject to an HTML
 * whitelist that allows only formatting tags and simple hyperlinks.
 */
public interface AuditIssueDefinition
{
    /**
     * This method returns the name of this issue type.
     *
     * @return The name of this issue type (e.g. "SQL injection").
     */
    String name();

    /**
     * This method returns a background description for this issue type.
     *
     * @return A background description for this type of issue, or {@code null}
     * if none applies. A limited set of HTML tags may be used.
     */
    String background();

    /**
     * This method returns a background description of the remediation for this
     * type of issue.
     *
     * @return A background description of the remediation for this type of
     * issue, or {@code null} if none applies. A limited set of HTML tags may
     * be used.
     */
    String remediation();

    /**
     * This method returns the typical issue severity level.
     *
     * @return The typical {@link AuditIssueSeverity} level.
     */
    AuditIssueSeverity typicalSeverity();

    /**
     * This method returns an index of the issue type. See the Burp Scanner
     * documentation for a listing of all the issue types.
     *
     * @return An index of the issue type.
     */
    int typeIndex();

    /**
     * This method can be used to create a default implementation of an audit
     * issue definition.
     *
     * @param name The name of the issue type.
     * @param background The background description for the type of issue.
     * @param remediation The background description of the remediation for
     * this type of issue.
     * @param typicalSeverity The typical {@link AuditIssueSeverity} level.
     * @return The audit issue definition.
     */
    static AuditIssueDefinition from(String name, String background, String remediation, AuditIssueSeverity typicalSeverity)
    {
        final int EXTENSION_GENERATED = 0x08000000;

        return new AuditIssueDefinition()
        {
            @Override
            public String name()
            {
                return name;
            }

            @Override
            public String background()
            {
                return background;
            }

            @Override
            public String remediation()
            {
                return remediation;
            }

            @Override
            public AuditIssueSeverity typicalSeverity()
            {
                return typicalSeverity;
            }

            @Override
            public int typeIndex()
            {
                return EXTENSION_GENERATED;
            }
        };
    }
}
